-- SQL Dump generated by Antigravity
-- Source: Pegem KPSS Genel Kültür Modüler Soru Bankası

INSERT INTO questions (category, source, question_no, question_text, options, correct_answer, has_image) VALUES
  ('tarih', 'Pegem-SoruBankasi-GK', 1, 'Aşağıdaki yerleşim birimlerinden hangisi Orta
Asya Türk kültürünün araştırılmasında önemli bir
etkiye sahip değildir?', '{"A": "Karasuk", "B": "Tagar", "C": "Andronova", "D": "Afanasyevo", "E": "Kültepe"}'::jsonb, 'E', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 2, 'I. Haristan
II. Belencer
III. Bolçu
Yukarıda verilen savaşlardan hangileri İslam Öncesi
Dönem’de Türklerle Araplar arasında yapılmıştır?', '{"A": "Yalnız I", "B": "Yalnız II", "C": "I ve II", "D": "I ve III", "E": "I, II ve III"}'::jsonb, 'C', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 3, 'Orta Asya Türk toplulukları arasında, göçebe bir
yaşamın olması;
I. geçim kaynaklarının hayvancılık olması,
II. yaşadıkları bölgenin karasal olması,
III. savaşçı özelliklerinin gelişmiş olması
durumlarından hangilerine dayandırılabilir?', '{"A": "Yalnız I", "B": "Yalnız II", "C": "I ve II", "D": "II ve III", "E": "I, II ve III"}'::jsonb, 'C', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 4, 'Aşağıdaki Türk hükümdarlarından hangisi
Avrupa’da hüküm sürmemiştir?', '{"A": "Uldız", "B": "Moyen-Çur", "C": "Boris Han", "D": "Bleda", "E": "Attila"}'::jsonb, 'B', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 5, 'İslam öncesinde, Türk ekonomisinde tarımın bu-
lunduğunu;
I. tohumluk buğday üretmeleri,
II. demirden saban ve orak yapmaları,
III. sulama kanalı inşa etmeleri
durumlarından hangileri kanıtlar?', '{"A": "Yalnız I", "B": "Yalnız II", "C": "I ve II", "D": "II ve III", "E": "I, II ve III"}'::jsonb, 'E', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 6, 'Göktürklerde hapis cezalarının kısa süreli olması
ve hukuk kurallarının yazılı hâle getirilmemesi aşa-
ğıdaki özelliklerden hangisi ile açıklanabilir?', '{"A": "Savaşçı karakter", "B": "Feodal yapı", "C": "Federatif anlayış", "D": "Veraset sistemi", "E": "Göçebe yaşam"}'::jsonb, 'E', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 7, 'Aşağıdaki Türk hükümdarlarından hangisi Orta
Asya’da devlet kurmamıştır?', '{"A": "Uldız", "B": "Bumin", "C": "İlteriş", "D": "Kutluk Bilge", "E": "Baga Tarkan"}'::jsonb, 'A', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 8, 'Burcu Öğretmen, beş öğrencisini boy sırasına uygun
dizerek en uzun boylu olana “devlet” adını vermiştir.
Ardından sınıfa, öğrencilerin her birinin devleti oluştu-
ran sosyal unsurları temsil ettiklerini belirtmiştir.
Buna göre “devlet” adlı en uzun boylu öğrenciden
sonra gelen uzun boylu öğrencinin adı aşağıdaki-
lerden hangisidir?', '{"A": "Boy", "B": "Oguş", "C": "Budun", "D": "Urug", "E": "İl"}'::jsonb, 'C', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 9, 'I. Eftalitler
II. Tabgaçlar
III. Tunguzlar
Yukarıdakilerden hangileri Türk devlet ve topluluk-
larından değildir?', '{"A": "Yalnız I", "B": "Yalnız III", "C": "I ve II", "D": "II ve III", "E": "I, II ve III"}'::jsonb, 'B', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 10, 'Aşağıdakilerden hangisi Uygurların yerleşik hayata
geçtiklerinin göstergesi olamaz?', '{"A": "Matbaa ve kağıdı kullanmaları", "B": "Tapınaklar yapmaları", "C": "Duvar resim sanatının gelişmesi", "D": "Yazıtlar dikmeleri", "E": "Emlak ve kira hukukunun gelişmesi"}'::jsonb, 'D', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 11, 'I. Uygur,
II. Hun,
III. Hazar
devletlerinden hangilerinin hükümdarları Manihe-
izm dinini benimsemiştir?', '{"A": "Yalnız I", "B": "Yalnız II", "C": "I ve III", "D": "II ve III", "E": "I, II ve III"}'::jsonb, 'A', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 12, 'Avrupa’da hüküm süren aşağıdaki Türk devlet ya
da topluluklarından hangisi Altınordu Devleti’nin
Türkleşmesine ve bugünkü Kazan Türklerinin orta-
ya çıkmasına etki etmiştir?', '{"A": "Tuna Bulgarları", "B": "İtil Bulgarları", "C": "Peçenekler", "D": "Avarlar", "E": "Hunlar"}'::jsonb, 'B', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 13, 'Arap seyyah İbn-i Fadlan’nın seyahatnamesinde
İslamlaşmasından bahsettiği Türk devleti aşağıda-
kilerden hangisidir?', '{"A": "İtil Bulgarları", "B": "Karahanlılar", "C": "Gazneliler", "D": "Akhunlar", "E": "Oğuzlar"}'::jsonb, 'A', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 14, 'Türk devlet ve hükümdarları ile ilgili verilen aşağı-
daki bilgilerden hangisi doğru değildir?', '{"A": "İslamiyet’i kabul eden ilk devlet İtil Bulgarlarıdır.", "B": "Attila; hükümdarlığı, babadan oğula geçen salta- nat sistemine dönüştürmüştür.", "C": "Hunlar ve Avarlar hem Asya hem de Avrupa’da devlet kurmuştur.", "D": "İstemi Yabgu Dönemi’nde ipek yolu egemenliği sağlanmıştır.", "E": "I. Köktürk Devleti Çin’e karşı bir isyan sonucu ku- rulmuştur."}'::jsonb, 'E', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 15, 'Orta Asya’da bulunan aşağıdaki yerleşim birimle-
rinden hangisi Türk devletlerine merkezlik yapma-
mıştır?', '{"A": "Ordu-balık", "B": "Hanbalık", "C": "Ötüken", "D": "Kaşgar", "E": "Turfan"}'::jsonb, 'B', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 16, 'Aşağıdaki Türk hükümdarlardan hangisi sahibi ol-
duğu devlete en parlak devrini yaşatmamıştır?', '{"A": "Attila", "B": "Mete", "C": "Bilge Kağan", "D": "Kutluk Kül Bilge", "E": "Moyen-Çur"}'::jsonb, 'D', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 17, 'Mete Han Dönemi’nde;
I. kurultayın oluşturulması,
II. orduda onluk sistemin kurulması,
III. Çin’i egemenliği altına almak yerine vergiye bağ-
lama
uygulamalarından hangileri teşkilatlanma faaliyet-
leri alanında gerçekleştirilmiştir?', '{"A": "I ve II", "B": "I ve III", "C": "Yalnız I", "D": "I, II ve III", "E": "Yalnız III"}'::jsonb, 'A', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 18, 'Aşağıdakilerden hangisi bir bölgede tarımsal faa-
liyetlerde bulunulduğunun kesin olarak kanıtı de-
ğildir?', '{"A": "Yerleşik yaşama geçmeleri", "B": "Tahıl öğütme taşları", "C": "Tohumluk tarım ürünlerini kullanmaları", "D": "Yaşadıkları bölgelerde orak, saban gibi aletlere rastlanması", "E": "Sulama kanalları inşa etmeleri"}'::jsonb, 'A', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 19, 'İslamiyet Öncesi Dönem’de yazısız hukuk kuralları
olan törelerin değiştirilemeyen kuralları arasında
aşağıdakilerden hangisi yer almaz?', '{"A": "Adalet", "B": "Kişilik", "C": "Eşitlik", "D": "Kut inancı", "E": "Faydalılık"}'::jsonb, 'D', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 20, 'Kumanlar (Kıpçaklar) ile ilgili olarak;
I. Memluk ve Delhi Türk Sultanlığı’nın kuruluşunda
etkili olmuşlardır.
II. Moğolların Türkleşmesinde etkili olmuşlardır.
III. Eyyubi Devleti’nin yıkılışında etkili olmuşlardır.
yargılarından hangileri söylenebilir?', '{"A": "Yalnız I", "B": "I ve II", "C": "I ve III", "D": "II ve III", "E": "I, II ve III"}'::jsonb, 'E', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 21, 'Aşağıdaki seçeneklerden hangisi Kavimler Göçü
ile ilgili doğru bir bilgi değildir?', '{"A": "Kuzey Hunları tarafından başlatılmıştır.", "B": "Avrupa’nın siyasi ve dini yapısını etkilemiştir.", "C": "Orta Çağ kapanmış, Yeni Çağ başlamıştır.", "D": "Avrupa’nın sosyal yapısı üzerinde etkili olmuştur.", "E": "Orta Asya’da Türk nüfusunun azalmasına yol aç- mıştır."}'::jsonb, 'C', false),
  ('tarih', 'Pegem-SoruBankasi-GK', 22, 'Aşağıdakilerden hangisi “Atımın ayak bastığı her yer
benim toprağımdır.” diyen Cesur Kavimlerin Efendi-
si Attila Dönemi gelişmeleri arasında yer almaz?', '{"A": "Bizans’ın ilk kez vergiye bağlanması", "B": "Bizans ile Margus ve Anatolius antlaşmalarının im- zalanması", "C": "Batı Roma üzerine Galya ve İtalya seferlerinin dü- zenlenmesi", "D": "Avrupa Hunları’nın en parlak döneminin yaşanma- sı", "E": "Doğu Roma üzerine 1. ve 2. Balkan Seferlerinin düzenlenmesi"}'::jsonb, 'A', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 1, 'Aşağıdakilerden hangisi Türkiye’nin bir Kuzey Ya-
rım Küre ülkesi olduğunun kesin kanıtı değildir?', '{"A": "Güneyindeki enlem derecelerinin kuzeyindeki en- lem derecelerinden küçük olması", "B": "Kuzeyine doğru gidildikçe çizgisel hızın azalması", "C": "Doğuya doğru gidildikçe meridyen derecelerinin artması", "D": "Güneş ışınlarının atmosferde tutulma oranının gü- neye doğru azalması", "E": "İki meridyen arası mesafenin güneye doğru geniş- lemesi"}'::jsonb, 'C', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 2, 'Sinop
Bursa
Iğdır
Manisa
Mersin
Türkiye haritası üzerinde verilen illerin hangisin-
de 21 Aralık tarihinde gündüz süresi diğerlerinden
daha kısadır?', '{"A": "Sinop", "B": "Bursa", "C": "Manisa", "D": "Iğdır", "E": "Mersin"}'::jsonb, 'E', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 3, 'Aşağıda Türkiye’nin coğrafi konumu ile ilgili bazı bilgi-
ler verilmiştir.
I. Yükseltisi batıdan doğuya doğru gidildikçe art-
maktadır.
II. Gölge yönü sürekli kuzeyi gösterir.
III. Dünya’da bilinen bor yataklarının %70’ten fazla-
sını barındırır.
IV. Dört mevsim belirgin olarak yaşanır.
Buna göre yukarıda verilen bilgilerden hangileri
Türkiye’nin özel (göreceli) konumuyla açıklanır?', '{"A": "I ve II", "B": "II ve III", "C": "I ve IV", "D": "I ve III", "E": "II ve IV"}'::jsonb, 'D', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 4, 'Tunceli
Türkiye haritası üzerinde Tunceli ilinin konumu veril-
miştir.
Buna göre, Tunceli’den yola çıkarak;
• Yengeç Dönencesi’ne yaklaşmak için,
• Başlangıç meridyeninden uzaklaşmak için,
• Tarih değiştirme çizgisine yaklaşmak için
hangi yöne doğru gidilmesi gerekir?', '{"A": "Kuzey-Batı", "B": "Güney", "C": "Güney-Batı", "D": "Kuzey-Doğu", "E": "Güney-Doğu"}'::jsonb, 'E', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 5, 'B D
Güneş, 23 Eylül’de 45° doğu meridyeninde yukarı-
daki konumda iken aynı anda Çanakkale’de yakla-
şık olarak hangi konumda olur?', '{"A": "", "B": "", "C": "B D B D B D", "D": "", "E": "B D B D"}'::jsonb, 'B', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 6, 'Kağızman
Gelibolu
Türkiye haritası üzerinde Gelibolu ve Kağızman ilçele-
rinin konumu verilmiştir.
Bu iki ilçe için,
I. Çizgisel hızları
II. Gündüz süreleri
III. Güneş ışınlarının atmosferde aldığı yol
bilgilerinden hangileri yıl boyunca aynıdır?', '{"A": "Yalnız III", "B": "I ve II", "C": "II ve III", "D": "I ve III", "E": "I, II ve III"}'::jsonb, 'E', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 7, 'Aşağıda bazı koordinat değerleri verilmiştir.
I. 43° Kuzey 43° Doğu
II. 38° Kuzey 38° Doğu
III. 34° Kuzey 44° Doğu
IV. 41° Kuzey 33° Doğu
Buna göre verilen coğrafi koordinat değerlerinden
hangileri Türkiye sınırları içerisinde yer almaz?', '{"A": "Yalnız I", "B": "I ve II", "C": "I ve III", "D": "II ve IV", "E": "III ve IV"}'::jsonb, 'C', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 8, 'IV
II
I
III
V
Türkiye haritası üzerinde verilen yerlerin hangisin-
de 21 Haziran tarihinde ok yönüne doğru gidildi-
ğinde hem gece süresi uzar hem de yerel saat ileri
olur?', '{"A": "I", "B": "II", "C": "III", "D": "IV", "E": "V"}'::jsonb, 'A', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 9, 'Sarıyer
Pazar
Şereflikoçhisar
Datça İskenderun
Yukarıdaki Türkiye haritası üzerinde beş farklı ilçe gös-
terilmiştir.
Buna göre bu ilçelerle ilgili verilen bilgilerden han-
gisi mutlak (matematik) konumun bir sonucudur?', '{"A": "Şereflikoçhisar’da donlu geçen gün sayısının Sarıyer’den fazla olması", "B": "Pazar’ın ocak ayı sıcaklık ortalamasının Şereflikoçhisar’dan fazla olması", "C": "İskenderun’un yıllık yağış miktarının Pazar’dan az olması", "D": "Şereflikoçhisar’ın temmuz ayı yağış ortalamasının Sarıyer’den az olması", "E": "Datça’nın ocak ayı sıcaklık ortalamasının Pazar’dan fazla olması"}'::jsonb, 'E', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 10, 'Türkiye, İstanbul ve Çanakkale Boğazlarına sahip ol-
masından dolayı bölgedeki jeopolitik ve jeostratejik
konumunu yükseltmiştir. Özellikle Karadeniz’e kıyısı
olan ülkelerin çoğu bu boğazları kullanabilmek için
Türkiye ile arasını iyi tutmaya çalışmıştır. Çünkü bu ül-
kelerin uluslararası sulara açılan tek kapısı Türkiye’de-
ki boğazlardır.
Buna göre aşağıda verilen ülkelerden hangisi Tür-
kiye’deki boğazları kullanmadan uluslararası su
yollarına ve okyanuslara çıkabilir?', '{"A": "Gürcistan", "B": "Rusya Federasyonu", "C": "Ukrayna", "D": "Bulgaristan", "E": "Romanya"}'::jsonb, 'B', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 11, 'Samsun
Kırşehir
Mersin
Yukarıdaki haritada aynı meridyen üzerinde yer alan
üç il merkezinin konumları verilmiştir.
Bu merkezler ile ilgili,
I. Başlangıç Meridyeni’ne en yakın yer Mersin’dir.
II. Çizgisel hız en fazla Samsun’dadır.
III. 21 Mart tarihinde Mersin’in gündüz uzunluğu
Kırşehir’den fazladır.
IV. Yer çekimi Kırşehir’e göre Samsun’da daha fazladır.
verilen bilgilerden hangileri yanlıştır?', '{"A": "I ve II", "B": "II, III ve IV", "C": "I ve IV", "D": "I, II ve III", "E": "I, III ve IV"}'::jsonb, 'D', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 12, 'II
IV
I
III
V
Yukarıdaki Türkiye haritası üzerinde verilen yerle-
rin hangisi ile ulusal saat arasında zaman farkı en
azdır?', '{"A": "I", "B": "II", "C": "III", "D": "IV", "E": "V Coğr"}'::jsonb, 'E', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 13, 'Türkiye’de herhangi bir noktaya dikilen çubuğun
gölgesinin yıl içerisinde hiçbir zaman sıfır olmama-
sının nedeni aşağıdakilerden hangisidir?', '{"A": "Türkiye’nin Kuzey Yarım Küre’de yer alması", "B": "Türkiye’nin Yengeç ve Oğlak Dönenceleri arasında olmaması", "C": "Başlangıç Meridyeni’nin doğusunda yer alması", "D": "Ortalama yükseltisinin ve engebenin fazla olması", "E": "Güneş ışınlarının atmosferde tutulma oranının faz- la olması"}'::jsonb, 'B', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 14, 'III
V
I
IV
II
27°Doğu
X
41°Kuzey
Türkiye haritası üzerinde verilen oklardan hangisi
yönünde gidilirse yukarıda coğrafi koordinatı veri-
len X merkezine ulaşılır?', '{"A": "I", "B": "II", "C": "III", "D": "IV", "E": "V"}'::jsonb, 'C', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 15, 'I. +4 saat diliminde yer alır.
II. En doğusu ile en batısı arasında 78 dakikalık fark
vardır.
III. En kuzey ile en güney ucu arası kuş uçumu 666
km’dir.
IV. Batısından doğuya doğru gidildikçe meridyen yay-
ları kısalır.
V. Güneyden kuzeye doğru paralel boyları uzar.
Türkiye’nin matematik konumu ile ilgili olarak yu-
karıda verilen bilgilerden hangileri yanlıştır?', '{"A": "I ve II", "B": "I, II ve III", "C": "III, IV ve V", "D": "I, II, IV ve V", "E": "I, II, III, IV ve V"}'::jsonb, 'D', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 16, 'Türkiye’de özel tarihler ile ilgili,
I. 23 Eylül’de sonbahar başlar.
II. 21 Aralık’tan sonra gündüzler kısalmaya başlar.
III. 21 Mart’ta en uzun gece yaşanır.
IV. 21 Haziran’da en kısa gece yaşanır.
bilgilerden hangileri doğrudur?', '{"A": "I ve II", "B": "II ve III", "C": "III ve IV", "D": "I ve III", "E": "I ve IV"}'::jsonb, 'E', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 17, 'I. Gündüz süresinin gece süresinden uzun olmaya
başladığı tarihtir.
II. Gece süresinin gündüz süresinden uzun olmaya
başladığı tarihtir.
III. Gündüzlerin kısalmaya başladığı tarihtir.
IV. Gecelerin kısalmaya başladığı tarihtir.
Yukarıda Türkiye’de görülen durumlar ile özel ta-
rihler eşleştirildiğinde hangi seçenek doğru olur?
21 Mart 23 Eylül 21 Haziran 21 Aralık', '{"A": "I II III IV", "B": "II III IV I", "C": "III II I IV", "D": "IV I III II", "E": "I IV II III"}'::jsonb, 'A', false),
  ('cografya', 'Pegem-SoruBankasi-GK', 18, 'Van
İzmir
Yaklaşık aynı enlem üzerinde bulunan İzmir ve
Van’ın coğrafi konumları düşünüldüğünde,
I. İzmir ve Van’da alacakaranlık süreleri farklıdır.
II. Van’ın ocak ayı ortalama sıcaklık değeri İzmir’den
düşüktür.
III. İzmir’in yıllık ortalama yağış miktarı Van’dan faz-
ladır.
bilgilerinden hangileri yanlıştır?', '{"A": "Yalnız I", "B": "Yalnız II", "C": "Yalnız III", "D": "I ve II", "E": "II ve III"}'::jsonb, 'A', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 1, 'Kişileri hukuk kurallarına uymaya zorlayan huku-
kun hangi özelliğidir?', '{"A": "Emirler içermesi", "B": "Yaptırımının maddi olması", "C": "Sosyal yaşamı düzenlemesi", "D": "Subjektif nitelikte olması", "E": "Yasaklar içermesi"}'::jsonb, 'B', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 2, 'Fiil ehliyetinin en önemli koşulu olan ayırt etme gü-
cünden yoksun olan kişiler aşağıdakilerden hangi-
sidir?', '{"A": "Sınırlı ehliyetsizler", "B": "Sınırlı ehliyetliler", "C": "Tam ehliyetsizler", "D": "Tam ehliyetliler", "E": "Nispi ehliyetliler"}'::jsonb, 'C', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 3, 'Tam ehliyetsiz olan A, son derece değerli bir tabloyu
çok düşük bir bedelle satın almıştır.
Bu işlemin geçerliliğiyle ilgili aşağıdaki ifadelerden
hangisi doğrudur?', '{"A": "İşlem hâkimin iptal kararı vermesine kadar geçer- lidir.", "B": "İşlem geçersizdir.", "C": "A’nın kanuni temsilcisi icazet verirse işlem geçerli hâle gelir.", "D": "İşlemin geçerli olması için A’nın, tabloyu 5 yıl sü- reyle elinde bulundurması gerekir.", "E": "İşlemin geçerli olması için, işlemi yapan diğer tara- fın, A’nın tam ehliyetsiz olduğunu işlemi yaparken bilmiyor olması gerekir."}'::jsonb, 'B', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 4, 'Bir somut olaya uygulanacak yazılı ya da yazılı ol-
mayan bir hukuk kuralının bulunmaması durumuna
verilen isim aşağıdakilerden hangisidir?', '{"A": "Hukuk boşluğu", "B": "Kural içi boşluk", "C": "Örtülü boşluk", "D": "Gerçek kanun boşluğu", "E": "Açık kanun boşluğu"}'::jsonb, 'A', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 5, 'Aşağıdakilerden hangisinin yaptırımı manevi değil-
dir?', '{"A": "Ahlak kurallarının", "B": "Hukuk kurallarının", "C": "Din kurallarının", "D": "Görgü kurallarının", "E": "Örf ve âdet kurallarının"}'::jsonb, 'B', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 6, 'Hâkimin hukuk yaratması ile ilgili aşağıdaki ifade-
lerden hangisi doğrudur?', '{"A": "Hâkimin hukuk yaratması, kanunda örtülü boşluk varsa mümkündür.", "B": "Hâkimin hukuk yaratması, hukuk boşluğu varsa mümkündür.", "C": "Hâkimin hukuk yaratması, kanunda kural içi boş- luk varsa mümkündür.", "D": "Kanun koyucu bir konuda kasıtlı sustuğu takdirde, hâkim susulan durumu doldurur.", "E": "Kanun metni ihtiyaca cevap vermiyorsa kanunda boşluk vardır ve hâkim bu boşluğu doldurur."}'::jsonb, 'B', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 7, 'Bir geleneğin örf ve âdet hukuku kuralı olabilmesi
için bulunması gereken unsurlar aşağıdakilerden
hangisinde tam ve doğru olarak verilmiştir?', '{"A": "Maddi unsur - Manevi unsur - Ahlak unsuru", "B": "Hukuki unsur - Manevi unsur - Genel uygulanabi- lirlik unsur", "C": "Hukuki unsur - Ahlaki unsur", "D": "Maddi unsur - Manevi unsur - Hukuki unsur", "E": "Maddi unsur - Manevi unsur - Toplumsal kabul unsuru"}'::jsonb, 'D', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 8, 'Fiil ehliyeti ile ilgili olarak aşağıdaki ifadelerden
hangisi doğrudur?', '{"A": "Kişi hak ehliyetiyle birlikte fiil ehliyetini de tam ola- rak kazanır.", "B": "Kişinin ergin olması onun fiil ehliyetine her zaman sahip olacağı anlamına gelmez.", "C": "Kişi kendi isteği ile her zaman fiil ehliyetini sınır- layabilir.", "D": "Kişinin ayırt etme gücüne sahip olmaması onun fiil ehliyetine sahip olmadığı anlamına gelmez.", "E": "Kişi kendi isteği ile fiil ehliyetinden tamamen vaz- geçebilir."}'::jsonb, 'B', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 9, 'İlk derece mahkemeleri tarafından verilmiş olup,
hatalı olduğu ileri sürülen kararların yeniden in-
celenmesini sağlamak üzere davanın taraflarına
tanınmış hukuki yolun genel adı aşağıdakilerden
hangisidir?', '{"A": "Kanuni hâkim güvencesi", "B": "Kanun yolu", "C": "Hâkimin takdir yetkisi", "D": "Kanun yararına bozma", "E": "Kanuni idare ilkesi"}'::jsonb, 'B', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 10, 'Aşağıdakilerden hangisi medeni hukukun alanına
girmez?', '{"A": "Kişiler hukuku", "B": "Miras hukuku", "C": "Sigorta hukuku", "D": "Eşya hukuku", "E": "Aile hukuku"}'::jsonb, 'C', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 11, 'Hükümsüzlük yaptırımı ile ilgili aşağıdaki ifadeler-
den hangisi yanlıştır?', '{"A": "Yokluk şeklinde ortaya çıkabilir.", "B": "Hukuk kurallarının belirlediği şekil şartlarına uyma- yan işlemler için söz konusudur.", "C": "Mutlak butlan şeklinde ortaya çıkabilir.", "D": "Nispi butlan şeklinde ortaya çıkabilir.", "E": "Hukuka aykırı idari işlemler için söz konusudur."}'::jsonb, 'E', false),
  ('vatandaslik', 'Pegem-SoruBankasi-GK', 12, 'Bir sözleşmenin kurulabilmesi için tarafların yap-
tıkları irade açıklamaları aşağıdakilerden hangisi-
dir?', '{"A": "İlan - Kabul", "B": "İlan - İhbar", "C": "İcaba davet - İcap", "D": "Teklif - İhbar", "E": "Teklif - Kabul"}'::jsonb, 'E', false);